using System;
using System.Collections.Generic;
using System.Text;

namespace DfuSe.Core
{
    public enum StDeviceErrors
    {
         STDEVICE_NOERROR = 0,
         STDEVICE_MEMORY = 1,
         STDEVICE_BADPARAMETER = 2,

         STDEVICE_NOTIMPLEMENTED = 3,
         STDEVICE_ENUMFINISHED = 4,
         STDEVICE_OPENDRIVERERROR = 5,

         STDEVICE_ERRORDESCRIPTORBUILDING = 6,
         STDEVICE_PIPECREATIONERROR = 7,
         STDEVICE_PIPERESETERROR = 8,
         STDEVICE_PIPEABORTERROR = 9,
         STDEVICE_STRINGDESCRIPTORERROR = 0xA,

         STDEVICE_DRIVERISCLOSED = 0xB,
         STDEVICE_VENDOR_RQ_PB = 0xC,
         STDEVICE_ERRORWHILEREADING = 0xD,
         STDEVICE_ERRORBEFOREREADING = 0xE,
         STDEVICE_ERRORWHILEWRITING = 0xF,
         STDEVICE_ERRORBEFOREWRITING = 0x10,
         STDEVICE_DEVICERESETERROR = 0x11,
         STDEVICE_CANTUSEUNPLUGEVENT = 0x12,
         STDEVICE_INCORRECTBUFFERSIZE = 0x13,
         STDEVICE_DESCRIPTORNOTFOUND = 0x14,
         STDEVICE_PIPESARECLOSED = 0x15,
         STDEVICE_PIPESAREOPEN = 0x16,
    }
}
